In [13]:
import pandas as pd
import requests
import time

from Bio import Entrez, SeqIO

In [14]:
df = pd.read_csv("download/t_common_variant.txt", sep = "\t", index_col = False)

In [15]:
df.head()

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Unnamed: 10
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,NaN
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,NaN
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,NaN
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,NaN

In [16]:
df_SNPs = df[["Chr", "SNP_position", "effect_allele", "alternate_allele"]]

In [17]:
df_SNPs

              Chr SNP_position effect_allele alternate_allele
0               6    142758601             T                G
1               1    155839054             C                T
2              12     40428561             G                T
3              12     40478652             G                T
4              12     40474147             C                T
...           ...          ...           ...              ...
1053  rs117896735            U            13                U
1054   rs12456492            U            21                U
1055    rs7155501            U            15                U
1056   rs10797576            U            21                U
1057   rs62120679            U            13                U

[1058 rows x 4 columns]

In [18]:
df_SNPs = df_SNPs.dropna()

In [19]:
df_SNPs = df_SNPs.reset_index(drop=False)[["Chr", "SNP_position", "effect_allele", "alternate_allele"]]

In [20]:
df_SNPs

              Chr SNP_position effect_allele alternate_allele
0               6    142758601             T                G
1               1    155839054             C                T
2              12     40428561             G                T
3              12     40478652             G                T
4              12     40474147             C                T
...           ...          ...           ...              ...
1053  rs117896735            U            13                U
1054   rs12456492            U            21                U
1055    rs7155501            U            15                U
1056   rs10797576            U            21                U
1057   rs62120679            U            13                U

[1058 rows x 4 columns]

In [21]:
df_copia = pd.DataFrame(columns = [i for i in df_SNPs])

In [22]:
df_copia

Empty DataFrame
Columns: [Chr, SNP_position, effect_allele, alternate_allele]
Index: []

In [23]:
df_SNPs_copia = pd.DataFrame(columns = [i for i in df_SNPs])

for i, fila in enumerate(df_SNPs["Chr"]):
    
    if "rs" in fila:
        continue
        
    else:
        df_SNPs_copia = pd.concat([df_SNPs_copia, df_SNPs.iloc[[i]]])

In [24]:
df_SNPs_copia

     Chr SNP_position effect_allele alternate_allele
0      6    142758601             T                G
1      1    155839054             C                T
2     12     40428561             G                T
3     12     40478652             G                T
4     12     40474147             C                T
...   ..          ...           ...              ...
1041  17     76425480             A                T
1042  18     31304318             T                G
1043  18     48683589             T                G
1044  20      6006041             T                C
1045  21     38852361             A                G

[1046 rows x 4 columns]

In [25]:
archivo_genoma = "Homo_sapiens.GRCh37.completo.fa"

genoma = SeqIO.index(archivo_genoma, "fasta")

In [34]:
cromosoma = "6"
pos = 142758601

secuencia_chr = genoma[cromosoma].seq
region = secuencia_chr[pos - 51 : pos + 49]

print(f"Cromosoma: {cromosoma}\nPosición: {pos}\nRegión sana: {region}")

Cromosoma: 6
Posición: 142758601
Región sana: TATATTTTCTTTTGTCACAGGCTTATTTATATTCATCTTCCACTGTGCTATGAAGGAGAATGTTCAGAAACAGTGGCGGCAGCATCTCTGCTGTGGTAGA