In [8]:
# pip install mygene
# pip install myvariant

In [1]:
import pandas as pd
import numpy as np
import requests
import time
import mygene
import myvariant

In [2]:
df = pd.read_csv("datosGene4PD/t_common_variant.txt", sep = "\t", index_col = False)

In [3]:
df.head(20)

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Unnamed: 10
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,NaN
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,NaN
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,NaN
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
5,14,SLC2A15,rs7304281,40465942,T,C,3.62E-54,12.05,8.35-17.41,24842889,NaN
6,12,LINC02471;LRRK2,rs2046932,40580440,G,A,1.63E-41,6.2,4.71-8.16,24842889,NaN
7,12,LRRK2,rs1491942,40620808,C,G,1.71E-41,6.2,4.71-8.16,24842889,NaN
8,12,LRRK2,rs34637584,40734202,G,A,4.46E-41,6.17,4.69-8.11,24842889,NaN
9,4,GPRIN3;SNCA,rs356220,90641340,T,C,8.88E-16,-,-,21044948,NaN
10,18,MAPT,rs8070724,44081064,A,G,7.45E-12,-,-,21044948,NaN
11,17,LINC02210-CRHR1,rs7215239,43767773,T,C,2.02E-11,-,-,21044948,NaN
12,4,GPRIN3;SNCA,rs356220,90641340,T,C,3.00E-11,1.38,0.07,24511991,NaN
13,17,LINC02210-CRHR1,rs417968,43728376,G,A,4.40E-11,-,-,21044948,NaN
14,14,SERPINA1,rs141620200,94845944,C,A,9.23E-11,1.08,1.035-1.117,28256260,NaN
15,14,SERPINA1,rs17580,94847262,T,A,9.23E-11,1.08,1.035-1.117,28256260,NaN
16,1,S1PR1;OLFM3,rs2338971,101880005,T,C,5.00E-10,0.76,0.03,24511991,NaN
17,19,MAPT,rs8070725,44081064,A,G,2.41E-09,0.66,0.58-0.74,24842889,NaN
18,17,MAPT,rs17563986,43991272,A,G,3.04E-09,0.66,0.58-0.75,24842889,NaN
19,17,SPPL2C,rs12185268,43923683,A,G,4.58E-09,0.66,0.58-0.75,24842889,NaN

In [4]:
# for i in df["SNPs_symbol"]:
#     print(i)

In [4]:
df_filtrado = df[df["SNPs_symbol"].str.startswith('rs')].reset_index(drop = True)

In [5]:
df_filtrado = df_filtrado.drop(["Unnamed: 10"], axis = 1)

In [6]:
df_filtrado

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889
...,...,...,...,...,...,...,...,...,...,...
1011,17,DNAH17,rs666463,76425480,A,T,2.90E-09,1.08,-,https://doi.org/10.1101/388165
1012,18,ASXL3,rs1941685,31304318,T,G,1.61E-08,1.05,-,https://doi.org/10.1101/388165
1013,18,MEX3C,rs8087969,48683589,T,G,1.46E-08,0.94,-,https://doi.org/10.1101/388165
1014,20,CRLS1,rs77351827,6006041,T,C,7.94E-09,1.08,-,https://doi.org/10.1101/388165
1015,21,DYRK1A,rs2248244,38852361,A,G,2.51E-11,1.07,-,https://doi.org/10.1101/388165

In [7]:
mv = myvariant.MyVariantInfo()

In [13]:
resultados = mv.querymany(['rs757765789'], scopes = 'dbsnp.rsid', fields = 'dbsnp', species = 'human')

In [22]:
resultados[0].keys()

dict_keys(['query', '_id', '_score', 'dbsnp'])

In [25]:
resultados[0]["query"]

'rs757765789'

In [24]:
resultados[0]["_id"]

'chr6:g.142758601T>G'

In [26]:
resultados[0]["_score"]

17.164398

In [29]:
resultados[0]["dbsnp"].keys()

dict_keys(['_license', 'alleles', 'alt', 'chrom', 'dbsnp_build', 'gene', 'hg19', 'ref', 'rsid', 'vartype'])

In [30]:
resultados[0]["dbsnp"]["_license"]

'http://bit.ly/2AqoLOc'

In [31]:
resultados[0]["dbsnp"]["alleles"]

[{'allele': 'T', 'freq': {'exac': 1.0, 'gnomad': 1.0, 'gnomad_exomes': 1.0}},
 {'allele': 'G', 'freq': {'exac': 0.0, 'gnomad': 0.0, 'gnomad_exomes': 0.0}}]

In [32]:
resultados[0]["dbsnp"]["alt"]

'G'

In [33]:
resultados[0]["dbsnp"]["chrom"]

'6'

In [34]:
resultados[0]["dbsnp"]["dbsnp_build"]

156

In [35]:
resultados[0]["dbsnp"]["gene"]

{'geneid': 57211,
 'is_pseudo': False,
 'name': 'adhesion G protein-coupled receptor G6',
 'rnas': [{'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3587,
    'seq_id': 'NM_001032394.3'},
   'hgvs': 'NM_001032394.3:c.3266=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1088,
      'seq_id': 'NP_001027566.2'}}},
   'protein_product': {'refseq': 'NP_001027566.2'},
   'refseq': 'NM_001032394.3',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3587,
    'seq_id': 'NM_001032395.3'},
   'hgvs': 'NM_001032395.3:c.3266=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1088,
      'seq_id': 'NP_001027567.2'}}},
   'protein_product': {'refseq': 'NP_001027567.2'},
   'refseq': 'NM_001032395.3',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3671,
    'seq_id': 'NM_020455.6'},
   'hgvs': 'NM_020455.6:c.3350=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1116,
      'seq_id': 'NP_065188.5'}}},
   'protein_product': {'refseq': 'NP_065188.5'},
   'refseq': 'NM_020455.6',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3671,
    'seq_id': 'NM_198569.3'},
   'hgvs': 'NM_198569.3:c.3350=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1116,
      'seq_id': 'NP_940971.2'}}},
   'protein_product': {'refseq': 'NP_940971.2'},
   'refseq': 'NM_198569.3',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3674,
    'seq_id': 'XM_005267061.4'},
   'hgvs': 'XM_005267061.4:c.3353=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1117,
      'seq_id': 'XP_005267118.1'}}},
   'protein_product': {'refseq': 'XP_005267118.1'},
   'refseq': 'XM_005267061.4',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3674,
    'seq_id': 'XM_006715516.3'},
   'hgvs': 'XM_006715516.3:c.3353=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1117,
      'seq_id': 'XP_006715579.1'}}},
   'protein_product': {'refseq': 'XP_006715579.1'},
   'refseq': 'XM_006715516.3',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3409,
    'seq_id': 'XM_006715517.3'},
   'hgvs': 'XM_006715517.3:c.3347=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1115,
      'seq_id': 'XP_006715580.1'}}},
   'protein_product': {'refseq': 'XP_006715580.1'},
   'refseq': 'XM_006715517.3',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3590,
    'seq_id': 'XM_006715518.3'},
   'hgvs': 'XM_006715518.3:c.3269=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1089,
      'seq_id': 'XP_006715581.1'}}},
   'protein_product': {'refseq': 'XP_006715581.1'},
   'refseq': 'XM_006715518.3',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3412,
    'seq_id': 'XM_011535964.2'},
   'hgvs': 'XM_011535964.2:c.3350=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1116,
      'seq_id': 'XP_011534266.1'}}},
   'protein_product': {'refseq': 'XP_011534266.1'},
   'refseq': 'XM_011535964.2',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'protein_product': {'refseq': 'XP_016866574.1'},
   'refseq': 'XM_017011085.2',
   'so': [{'accession': 'SO:0002152',
     'name': 'genic_downstream_transcript_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3328,
    'seq_id': 'XM_047419102.1'},
   'hgvs': 'XM_047419102.1:c.3266=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1088,
      'seq_id': 'XP_047275058.1'}}},
   'protein_product': {'refseq': 'XP_047275058.1'},
   'refseq': 'XM_047419102.1',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3412,
    'seq_id': 'XM_047419103.1'},
   'hgvs': 'XM_047419103.1:c.3350=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1116,
      'seq_id': 'XP_047275059.1'}}},
   'protein_product': {'refseq': 'XP_047275059.1'},
   'refseq': 'XM_047419103.1',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3325,
    'seq_id': 'XM_047419104.1'},
   'hgvs': 'XM_047419104.1:c.3263=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1087,
      'seq_id': 'XP_047275060.1'}}},
   'protein_product': {'refseq': 'XP_047275060.1'},
   'refseq': 'XM_047419104.1',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3409,
    'seq_id': 'XM_047419105.1'},
   'hgvs': 'XM_047419105.1:c.3347=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1115,
      'seq_id': 'XP_047275061.1'}}},
   'protein_product': {'refseq': 'XP_047275061.1'},
   'refseq': 'XM_047419105.1',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3590,
    'seq_id': 'XM_047419106.1'},
   'hgvs': 'XM_047419106.1:c.3269=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1089,
      'seq_id': 'XP_047275062.1'}}},
   'protein_product': {'refseq': 'XP_047275062.1'},
   'refseq': 'XM_047419106.1',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]},
  {'codon_aligned_transcript_change': {'deleted_sequence': 'ATG',
    'inserted_sequence': 'ATG',
    'position': 3328,
    'seq_id': 'XM_047419107.1'},
   'hgvs': 'XM_047419107.1:c.3266=',
   'protein': {'variant': {'spdi': {'deleted_sequence': 'M',
      'inserted_sequence': 'M',
      'position': 1088,
      'seq_id': 'XP_047275063.1'}}},
   'protein_product': {'refseq': 'XP_047275063.1'},
   'refseq': 'XM_047419107.1',
   'so': [{'accession': 'SO:0001580', 'name': 'coding_sequence_variant'}]}],
 'strand': '+',
 'symbol': 'ADGRG6'}

In [36]:
resultados[0]["dbsnp"]["hg19"]

{'end': 142758601, 'start': 142758601}

In [37]:
resultados[0]["dbsnp"]["ref"]

'T'

In [38]:
resultados[0]["dbsnp"]["rsid"]

'rs757765789'

In [39]:
resultados[0]["dbsnp"]["vartype"]

'snv'

In [9]:
mg = mygene.MyGeneInfo()

In [41]:
resultados_genes = mg.querymany(['ADGRG6'], scopes = "symbol,alias", fields = "genomic_pos_hg19", species = "human")

In [42]:
resultados_genes

[{'query': 'ADGRG6',
  '_id': '57211',
  '_score': 17.488766,
  'genomic_pos_hg19': {'chr': '6',
   'end': 142767403,
   'start': 142622991,
   'strand': 1}}]

In [43]:
resultados_genes2 = mg.querymany(['GPR126'], scopes = "symbol,alias", fields = "genomic_pos_hg19", species = "human")

In [44]:
resultados_genes2

[{'query': 'GPR126',
  '_id': '57211',
  '_score': 19.08153,
  'genomic_pos_hg19': {'chr': '6',
   'end': 142767403,
   'start': 142622991,
   'strand': 1}}]

In [14]:
lista_rs = list(df_filtrado["SNPs_symbol"])

In [17]:
resultados = mv.querymany(lista_rs, scopes = 'dbsnp.rsid', fields = 'dbsnp', species = 'human')

507 input query terms found dup hits:	[('rs202015799', 2), ('rs1994090', 9), ('rs2708453', 4), ('rs4768212', 4), ('rs7304281', 2), ('rs204
1 input query terms found no hit:	['rs2740594c']

In [11]:
df.head(20)

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Unnamed: 10
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,NaN
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,NaN
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,NaN
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
5,14,SLC2A15,rs7304281,40465942,T,C,3.62E-54,12.05,8.35-17.41,24842889,NaN
6,12,LINC02471;LRRK2,rs2046932,40580440,G,A,1.63E-41,6.2,4.71-8.16,24842889,NaN
7,12,LRRK2,rs1491942,40620808,C,G,1.71E-41,6.2,4.71-8.16,24842889,NaN
8,12,LRRK2,rs34637584,40734202,G,A,4.46E-41,6.17,4.69-8.11,24842889,NaN
9,4,GPRIN3;SNCA,rs356220,90641340,T,C,8.88E-16,-,-,21044948,NaN
10,18,MAPT,rs8070724,44081064,A,G,7.45E-12,-,-,21044948,NaN
11,17,LINC02210-CRHR1,rs7215239,43767773,T,C,2.02E-11,-,-,21044948,NaN
12,4,GPRIN3;SNCA,rs356220,90641340,T,C,3.00E-11,1.38,0.07,24511991,NaN
13,17,LINC02210-CRHR1,rs417968,43728376,G,A,4.40E-11,-,-,21044948,NaN
14,14,SERPINA1,rs141620200,94845944,C,A,9.23E-11,1.08,1.035-1.117,28256260,NaN
15,14,SERPINA1,rs17580,94847262,T,A,9.23E-11,1.08,1.035-1.117,28256260,NaN
16,1,S1PR1;OLFM3,rs2338971,101880005,T,C,5.00E-10,0.76,0.03,24511991,NaN
17,19,MAPT,rs8070725,44081064,A,G,2.41E-09,0.66,0.58-0.74,24842889,NaN
18,17,MAPT,rs17563986,43991272,A,G,3.04E-09,0.66,0.58-0.75,24842889,NaN
19,17,SPPL2C,rs12185268,43923683,A,G,4.58E-09,0.66,0.58-0.75,24842889,NaN

In [12]:
resultado = mv.querymany(['rs2046932'], scopes = 'dbsnp.rsid', fields = 'dbsnp', species = 'human')

1 input query terms found dup hits:	[('rs2046932', 2)]

In [22]:
resultado[1].keys()

dict_keys(['query', '_id', '_score', 'dbsnp'])

In [27]:
# resultado

In [36]:
df_filtrado = df[df["SNPs_symbol"].str.startswith('rs')].reset_index(drop = True)

In [37]:
df_filtrado

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Unnamed: 10
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,NaN
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,NaN
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,NaN
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1011,17,DNAH17,rs666463,76425480,A,T,2.90E-09,1.08,-,https://doi.org/10.1101/388165,NaN
1012,18,ASXL3,rs1941685,31304318,T,G,1.61E-08,1.05,-,https://doi.org/10.1101/388165,NaN
1013,18,MEX3C,rs8087969,48683589,T,G,1.46E-08,0.94,-,https://doi.org/10.1101/388165,NaN
1014,20,CRLS1,rs77351827,6006041,T,C,7.94E-09,1.08,-,https://doi.org/10.1101/388165,NaN
1015,21,DYRK1A,rs2248244,38852361,A,G,2.51E-11,1.07,-,https://doi.org/10.1101/388165,NaN

In [7]:
df_filtrado = df_filtrado.dropna(subset = ['gene_symbol']).reset_index(drop = True)

In [8]:
df_filtrado

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889
...,...,...,...,...,...,...,...,...,...,...
1009,17,DNAH17,rs666463,76425480,A,T,2.90E-09,1.08,-,https://doi.org/10.1101/388165
1010,18,ASXL3,rs1941685,31304318,T,G,1.61E-08,1.05,-,https://doi.org/10.1101/388165
1011,18,MEX3C,rs8087969,48683589,T,G,1.46E-08,0.94,-,https://doi.org/10.1101/388165
1012,20,CRLS1,rs77351827,6006041,T,C,7.94E-09,1.08,-,https://doi.org/10.1101/388165
1013,21,DYRK1A,rs2248244,38852361,A,G,2.51E-11,1.07,-,https://doi.org/10.1101/388165

In [12]:
df_filtrado = df_filtrado[~df_filtrado["gene_symbol"].str.contains(';')].reset_index(drop = True)

In [13]:
df_filtrado

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Unnamed: 10
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,NaN
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,NaN
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,NaN
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
...,...,...,...,...,...,...,...,...,...,...,...
723,17,DNAH17,rs666463,76425480,A,T,2.90E-09,1.08,-,https://doi.org/10.1101/388165,NaN
724,18,ASXL3,rs1941685,31304318,T,G,1.61E-08,1.05,-,https://doi.org/10.1101/388165,NaN
725,18,MEX3C,rs8087969,48683589,T,G,1.46E-08,0.94,-,https://doi.org/10.1101/388165,NaN
726,20,CRLS1,rs77351827,6006041,T,C,7.94E-09,1.08,-,https://doi.org/10.1101/388165,NaN
727,21,DYRK1A,rs2248244,38852361,A,G,2.51E-11,1.07,-,https://doi.org/10.1101/388165,NaN

In [14]:
df_filtrado = df_filtrado[~df_filtrado["gene_symbol"].str.contains(',')].reset_index(drop = True)

In [15]:
df_filtrado

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Unnamed: 10
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,NaN
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,NaN
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,NaN
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
...,...,...,...,...,...,...,...,...,...,...,...
710,17,DNAH17,rs666463,76425480,A,T,2.90E-09,1.08,-,https://doi.org/10.1101/388165,NaN
711,18,ASXL3,rs1941685,31304318,T,G,1.61E-08,1.05,-,https://doi.org/10.1101/388165,NaN
712,18,MEX3C,rs8087969,48683589,T,G,1.46E-08,0.94,-,https://doi.org/10.1101/388165,NaN
713,20,CRLS1,rs77351827,6006041,T,C,7.94E-09,1.08,-,https://doi.org/10.1101/388165,NaN
714,21,DYRK1A,rs2248244,38852361,A,G,2.51E-11,1.07,-,https://doi.org/10.1101/388165,NaN

In [48]:
for i in range(len(df_filtrado)):
    if 'dist' in df_filtrado.iloc[i]["gene_symbol"]:
        print(i)

99

In [49]:
df_filtrado.iloc[99]

Chr                               4
gene_symbol          SNCA(dist=796)
SNPs_symbol               rs8180209
SNP_position               90644454
effect_allele                     A
alternate_allele                  G
joint_phase_P              1.02E-32
joint_phase_OR                 0.71
joint_phase_OR_CI                 -
pubMed_ID                  28011712
Unnamed: 10                     NaN
Name: 99, dtype: object

In [50]:
resultado = mv.querymany(['rs8180209'], scopes = 'dbsnp.rsid', fields = 'dbsnp', species = 'human')

1 input query terms found dup hits:	[('rs8180209', 2)]

In [57]:
resultado[0]

{'query': 'rs8180209',
 '_id': 'chr4:g.90644454A>T',
 '_score': 17.164743,
 'dbsnp': {'_license': 'http://bit.ly/2AqoLOc',
  'alleles': [{'allele': 'A',
    'freq': {'1000g': 0.616,
     'alspac': 0.922,
     'chileans': 0.676,
     'dbgap_popfreq': 0.89,
     'estonian': 0.949,
     'genome_dk': 0.95,
     'gnomad': 0.763,
     'gonl': 0.918,
     'hapmap': 0.558,
     'korean': 0.476,
     'northernsweden': 0.915,
     'page_study': 0.582,
     'prjeb37584': 0.46,
     'qatari': 0.722,
     'sgdp_prj': 0.318,
     'siberian': 0.417,
     'tommo': 0.41,
     'topmed': 0.735,
     'twinsuk': 0.931,
     'vietnamese': 0.56}},
   {'allele': 'G',
    'freq': {'1000g': 0.384,
     'alspac': 0.078,
     'chileans': 0.324,
     'dbgap_popfreq': 0.11,
     'estonian': 0.051,
     'genome_dk': 0.05,
     'gnomad': 0.237,
     'gonl': 0.082,
     'hapmap': 0.442,
     'korean': 0.524,
     'northernsweden': 0.085,
     'page_study': 0.418,
     'prjeb37584': 0.54,
     'qatari': 0.278,
     'sgdp_prj': 0.682,
     'siberian': 0.583,
     'tommo': 0.59,
     'topmed': 0.265,
     'twinsuk': 0.069,
     'vietnamese': 0.44}},
   {'allele': 'T', 'freq': {'korean': 0.0}}],
  'alt': 'T',
  'chrom': '4',
  'citations': 32652860,
  'dbsnp_build': 156,
  'dbsnp_merges': {'date': '2008-05-24T15:17Z',
   'rsid': 'rs58302076',
   'rv': 130},
  'gene': {'geneid': 124900602,
   'is_pseudo': False,
   'name': 'uncharacterized LOC124900602',
   'rnas': [{'refseq': 'XR_001741764.2',
     'so': [{'accession': 'SO:0002152',
       'name': 'genic_downstream_transcript_variant'}]},
    {'refseq': 'XR_007058465.1',
     'so': [{'accession': 'SO:0002152',
       'name': 'genic_downstream_transcript_variant'}]},
    {'codon_aligned_transcript_change': {'deleted_sequence': 'A',
      'inserted_sequence': 'A',
      'position': 13179,
      'seq_id': 'XR_007058466.1'},
     'hgvs': 'XR_007058466.1:n.13180=',
     'refseq': 'XR_007058466.1',
     'so': [{'accession': 'SO:0001619',
       'name': 'non_coding_transcript_variant'}]},
    {'refseq': 'XR_938983.2',
     'so': [{'accession': 'SO:0002152',
       'name': 'genic_downstream_transcript_variant'}]}],
   'strand': '+',
   'symbol': 'LOC124900602'},
  'hg19': {'end': 90644454, 'start': 90644454},
  'ref': 'A',
  'rsid': 'rs8180209',
  'vartype': 'snv'}}

In [52]:
resultados_genes = mg.querymany(['124900602'], scopes = "entrezgene", fields = "symbol,genomic_pos_hg19", species = "human")

In [53]:
resultados_genes

[{'query': '124900602',
  '_id': '124900602',
  '_score': 27.401579,
  'symbol': 'LOC124900602'}]

In [54]:
resultados_genes = mg.querymany(['LOC124900602'], scopes = "symbol,alias", fields = "genomic_pos_hg19", species = "human")

In [55]:
resultados_genes

[{'query': 'LOC124900602', '_id': '124900602', '_score': 27.444014}]

In [9]:
def busca_rsIDs(df):
    
    lista_rsids = df["SNPs_symbol"].unique().tolist()

    mv = myvariant.MyVariantInfo()

    resultados = mv.querymany(lista_rsids, scopes = "dbsnp.rsid", fields = "dbsnp", species = "human")

    diccionario_snps = {}

    cromosomas_validos = [str(i) for i in range(1, 23)] + ["X", "Y", "MT"]

    bases_validas = ["A", "C", "G", "T", "a", "c", "g", "t"]

    for resultado in resultados:
        rsid = resultado.get("query")

        if "notfound" in resultado:
            continue

        info_dbsnp = resultado.get("dbsnp", {})

        hg19 = info_dbsnp.get("hg19", {})

        if not hg19:
            continue

        if isinstance(hg19, list):
            hg19 = hg19[0]

        cromosoma = str(info_dbsnp.get("chrom"))
        if cromosoma not in cromosomas_validos:
            continue

        pos_hg19 = hg19.get("start")

        ef_allele = info_dbsnp.get("ref", '')
        alt_allele = info_dbsnp.get("alt", '')

        if ef_allele not in bases_validas or alt_allele not in bases_validas:
            continue

        gene_info = info_dbsnp.get("gene", {})
        gene_symbol = "inter"

        if isinstance(gene_info, dict):
            gene_symbol = gene_info.get("symbol", "inter")

        elif isinstance(gene_info, list):
            gene_symbol = gene_info[0].get("symbol", "inter")

        if rsid not in diccionario_snps:

            diccionario_snps[rsid] = {"SNPs_symbol": rsid, "Chr_corr": cromosoma, "SNP_position_corr": pos_hg19, "Effect_allele_corr": ef_allele, "Alternate_allele_corr": [alt_allele], "Gene_symbol_corr": gene_symbol}

        else:

            if alt_allele not in diccionario_snps[rsid]["Alternate_allele_corr"]:
                diccionario_snps[rsid]["Alternate_allele_corr"].append(alt_allele)

    datos_corregidos = list(diccionario_snps.values())

    return pd.DataFrame(datos_corregidos)

In [10]:
df_corr = busca_rsIDs(df_filtrado)

474 input query terms found dup hits:	[('rs202015799', 2), ('rs1994090', 3), ('rs2708453', 2), ('rs4768212', 2), ('rs7304281', 2), ('rs204
1 input query terms found no hit:	['rs2740594c']

In [11]:
df_corr

,SNPs_symbol,Chr_corr,SNP_position_corr,Effect_allele_corr,Alternate_allele_corr,Gene_symbol_corr
0,rs757765789,6,142758601,T,[G],ADGRG6
1,rs202015799,1,155839054,C,"[G, T]",SYT11
2,rs1994090,12,40428561,G,"[A, T, C]",SLC2A13
3,rs2708453,12,40478652,G,"[A, T]",SLC2A13
4,rs4768212,12,40474147,C,"[A, T]",SLC2A13
...,...,...,...,...,...,...
881,rs666463,17,76425480,A,[T],DNAH17
882,rs1941685,18,31304318,G,"[T, C]",ASXL3
883,rs8087969,18,48683589,T,"[G, A]",inter
884,rs77351827,20,6006041,C,[T],CRLS1
885,rs2248244,21,38852361,G,[A],DYRK1A

In [12]:
def extrae_coords_inicio_fin_alternativa(df_SNPs, lista_unicos_snps):

    mg = mygene.MyGeneInfo()
    
    resultados_coords = mg.querymany(lista_unicos_snps, scopes = "symbol,alias", fields = "genomic_pos_hg19", species = "human")
    
    coords_genes = []
    no_encontrados = []
    
    for resultado in resultados_coords:

        gen = resultado.get("query")
        
        if resultado.get("notfound"):
            if gen not in no_encontrados:
                no_encontrados.append(gen)
            continue
    
        posiciones = resultado.get("genomic_pos_hg19")
        
        if not posiciones:
            continue
    
        if not isinstance(posiciones, list):
            posiciones = [posiciones]
    
        for pos in posiciones:
            if pos.get("chr"):
                coords_genes.append({"gene_symbol": gen, "chr": str(pos.get("chr")), "inicio": pos.get("start"), "fin": pos.get("end"), "cadena": pos.get("strand")})
    
        if gen in no_encontrados:
            no_encontrados.remove(gen)


    recuperados = [gen.replace('LOC', '') for gen in no_encontrados if 'LOC' in gen]

    if recuperados:
        recuperados_coords_aux = mg.querymany(recuperados, scopes = "entrezgene", fields = "symbol,genomic_pos_hg19", species = "human")
        nuevos_symbols = [res["symbol"] for res in recuperados_coords_aux if not res.get("notfound")]

        if nuevos_symbols:
            recuperados_coords = mg.querymany(nuevos_symbols, scopes = "symbol,alias", fields = "genomic_pos_hg19", species = "human")

            for resultado in recuperados_coords:
        
                gen = "LOC" + str(resultado.get("_id"))
        
                posiciones = resultado.get("genomic_pos_hg19")
        
                if not posiciones:
                    continue
    
                if not isinstance(posiciones, list):
                    posiciones = [posiciones]
    
                for pos in posiciones:
                    if pos.get("chr"):
                        coords_genes.append({"gene_symbol": gen, "chr": str(pos.get("chr")), "inicio": pos.get("start"), "fin": pos.get("end"), "cadena": pos.get("strand")})
    
                if gen in no_encontrados:
                    no_encontrados.remove(gen)

    df_coords = pd.DataFrame(coords_genes)

    df_coords = df_coords.drop_duplicates().reset_index(drop = True)

    return df_coords, no_encontrados

In [13]:
lista_unicos_snps = df_corr["Gene_symbol_corr"].unique().tolist()

In [14]:
df_coords, no_encontrados = extrae_coords_inicio_fin_alternativa(df_corr, lista_unicos_snps)

19 input query terms found dup hits:	[('CAST', 4), ('BST1', 2), ('MAPT-AS1', 4), ('BALR6', 2), ('DLG2', 2), ('BORCS7-ASMT', 2), ('RAI1',
4 input query terms found no hit:	['inter', 'LOC100287944', 'LOC105373058', 'LOC101929200']

In [15]:
df_coords

    gene_symbol chr     inicio        fin  cadena
0        ADGRG6   6  142622991  142767403       1
1         SYT11   1  155829300  155854990       1
2       SLC2A13  12   40148823   40499891      -1
3         LRRK2  12   40590546   40763087       1
4      RAP1GAP2  17    2680350    2941033       1
..          ...  ..        ...        ...     ...
394       BRIP1  17   59758627   59940882      -1
395      DNAH17  17   76419778   76573476      -1
396       ASXL3  18   31158579   31331156       1
397       CRLS1  20    5986736    6020699       1
398      DYRK1A  21   38738092   38889753       1

[399 rows x 5 columns]

In [16]:
df_union = pd.merge(df_corr, df_coords, left_on = "Gene_symbol_corr", right_on = "gene_symbol", how = "left")

In [17]:
df_union

,SNPs_symbol,Chr_corr,SNP_position_corr,Effect_allele_corr,Alternate_allele_corr,Gene_symbol_corr,gene_symbol,chr,inicio,fin,cadena
0,rs757765789,6,142758601,T,[G],ADGRG6,ADGRG6,6,142622991.0,142767403.0,1.0
1,rs202015799,1,155839054,C,"[G, T]",SYT11,SYT11,1,155829300.0,155854990.0,1.0
2,rs1994090,12,40428561,G,"[A, T, C]",SLC2A13,SLC2A13,12,40148823.0,40499891.0,-1.0
3,rs2708453,12,40478652,G,"[A, T]",SLC2A13,SLC2A13,12,40148823.0,40499891.0,-1.0
4,rs4768212,12,40474147,C,"[A, T]",SLC2A13,SLC2A13,12,40148823.0,40499891.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...
1083,rs666463,17,76425480,A,[T],DNAH17,DNAH17,17,76419778.0,76573476.0,-1.0
1084,rs1941685,18,31304318,G,"[T, C]",ASXL3,ASXL3,18,31158579.0,31331156.0,1.0
1085,rs8087969,18,48683589,T,"[G, A]",inter,NaN,NaN,NaN,NaN,NaN
1086,rs77351827,20,6006041,C,[T],CRLS1,CRLS1,20,5986736.0,6020699.0,1.0
1087,rs2248244,21,38852361,G,[A],DYRK1A,DYRK1A,21,38738092.0,38889753.0,1.0

In [29]:
df_nuevo = pd.merge(df_filtrado, df_union, on = "SNPs_symbol", how = "left")

In [30]:
df_nuevo

,Chr,gene_symbol_x,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Chr_corr,SNP_position_corr,Effect_allele_corr,Alternate_allele_corr,Gene_symbol_corr,gene_symbol_y,chr,inicio,fin,cadena
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,6,142758601.0,T,[G],ADGRG6,ADGRG6,6,142622991.0,142767403.0,1.0
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,1,155839054.0,C,"[G, T]",SYT11,SYT11,1,155829300.0,155854990.0,1.0
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,12,40428561.0,G,"[A, T, C]",SLC2A13,SLC2A13,12,40148823.0,40499891.0,-1.0
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,12,40478652.0,G,"[A, T]",SLC2A13,SLC2A13,12,40148823.0,40499891.0,-1.0
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,12,40474147.0,C,"[A, T]",SLC2A13,SLC2A13,12,40148823.0,40499891.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1246,17,DNAH17,rs666463,76425480,A,T,2.90E-09,1.08,-,https://doi.org/10.1101/388165,17,76425480.0,A,[T],DNAH17,DNAH17,17,76419778.0,76573476.0,-1.0
1247,18,ASXL3,rs1941685,31304318,T,G,1.61E-08,1.05,-,https://doi.org/10.1101/388165,18,31304318.0,G,"[T, C]",ASXL3,ASXL3,18,31158579.0,31331156.0,1.0
1248,18,MEX3C,rs8087969,48683589,T,G,1.46E-08,0.94,-,https://doi.org/10.1101/388165,18,48683589.0,T,"[G, A]",inter,NaN,NaN,NaN,NaN,NaN
1249,20,CRLS1,rs77351827,6006041,T,C,7.94E-09,1.08,-,https://doi.org/10.1101/388165,20,6006041.0,C,[T],CRLS1,CRLS1,20,5986736.0,6020699.0,1.0
1250,21,DYRK1A,rs2248244,38852361,A,G,2.51E-11,1.07,-,https://doi.org/10.1101/388165,21,38852361.0,G,[A],DYRK1A,DYRK1A,21,38738092.0,38889753.0,1.0

In [31]:
df_nuevo = df_nuevo[["Chr", "gene_symbol_x", "SNPs_symbol", "SNP_position", "effect_allele", "alternate_allele", "Chr_corr", "inicio", "SNP_position_corr", "fin", "Effect_allele_corr", "Alternate_allele_corr", "Gene_symbol_corr", "fin"]]

In [24]:
# df_nuevo = df_nuevo.drop("gene_symbol_y", axis = 1)

In [32]:
df_nuevo

,Chr,gene_symbol_x,SNPs_symbol,SNP_position,effect_allele,alternate_allele,Chr_corr,inicio,SNP_position_corr,fin,Effect_allele_corr,Alternate_allele_corr,Gene_symbol_corr,fin
0,6,GPR126,rs757765789,142758601,T,G,6,142622991.0,142758601.0,142767403.0,T,[G],ADGRG6,142767403.0
1,1,SYT11,rs202015799,155839054,C,T,1,155829300.0,155839054.0,155854990.0,C,"[G, T]",SYT11,155854990.0
2,12,SLC2A13,rs1994090,40428561,G,T,12,40148823.0,40428561.0,40499891.0,G,"[A, T, C]",SLC2A13,40499891.0
3,12,SLC2A13,rs2708453,40478652,G,T,12,40148823.0,40478652.0,40499891.0,G,"[A, T]",SLC2A13,40499891.0
4,12,SLC2A13,rs4768212,40474147,C,T,12,40148823.0,40474147.0,40499891.0,C,"[A, T]",SLC2A13,40499891.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1246,17,DNAH17,rs666463,76425480,A,T,17,76419778.0,76425480.0,76573476.0,A,[T],DNAH17,76573476.0
1247,18,ASXL3,rs1941685,31304318,T,G,18,31158579.0,31304318.0,31331156.0,G,"[T, C]",ASXL3,31331156.0
1248,18,MEX3C,rs8087969,48683589,T,G,18,NaN,48683589.0,NaN,T,"[G, A]",inter,NaN
1249,20,CRLS1,rs77351827,6006041,T,C,20,5986736.0,6006041.0,6020699.0,C,[T],CRLS1,6020699.0
1250,21,DYRK1A,rs2248244,38852361,A,G,21,38738092.0,38852361.0,38889753.0,G,[A],DYRK1A,38889753.0

In [26]:
# df_puro = df_nuevo.drop("Unnamed: 10", axis = 1)

In [39]:
df_puro = df_nuevo.dropna(subset = ["SNP_position_corr"]).reset_index(drop = True)
df_puro = df_puro.dropna(subset = ["inicio", "fin"]).reset_index(drop = True)

In [40]:
df_puro

,Chr,gene_symbol_x,SNPs_symbol,SNP_position,effect_allele,alternate_allele,Chr_corr,inicio,SNP_position_corr,fin,Effect_allele_corr,Alternate_allele_corr,Gene_symbol_corr,fin
0,6,GPR126,rs757765789,142758601,T,G,6,142622991.0,142758601.0,142767403.0,T,[G],ADGRG6,142767403.0
1,1,SYT11,rs202015799,155839054,C,T,1,155829300.0,155839054.0,155854990.0,C,"[G, T]",SYT11,155854990.0
2,12,SLC2A13,rs1994090,40428561,G,T,12,40148823.0,40428561.0,40499891.0,G,"[A, T, C]",SLC2A13,40499891.0
3,12,SLC2A13,rs2708453,40478652,G,T,12,40148823.0,40478652.0,40499891.0,G,"[A, T]",SLC2A13,40499891.0
4,12,SLC2A13,rs4768212,40474147,C,T,12,40148823.0,40474147.0,40499891.0,C,"[A, T]",SLC2A13,40499891.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
904,17,BRIP1,rs61169879,59917366,T,C,17,59758627.0,59917366.0,59940882.0,C,"[A, T]",BRIP1,59940882.0
905,17,DNAH17,rs666463,76425480,A,T,17,76419778.0,76425480.0,76573476.0,A,[T],DNAH17,76573476.0
906,18,ASXL3,rs1941685,31304318,T,G,18,31158579.0,31304318.0,31331156.0,G,"[T, C]",ASXL3,31331156.0
907,20,CRLS1,rs77351827,6006041,T,C,20,5986736.0,6006041.0,6020699.0,C,[T],CRLS1,6020699.0
908,21,DYRK1A,rs2248244,38852361,A,G,21,38738092.0,38852361.0,38889753.0,G,[A],DYRK1A,38889753.0

In [41]:
df_puro["inicio"] = df_puro["inicio"].astype(int)
df_puro["fin"] = df_puro["fin"].astype(int)

In [44]:
def valida_alelos_SNP(fila):

    effect_allele_original = fila["effect_allele"]
    alternate_allele_original = fila["alternate_allele"]
    effect_allele_rsID = fila["Effect_allele_corr"]
    alternate_allele_rsID = fila["Alternate_allele_corr"]

    alelos_original = [effect_allele_original, alternate_allele_original]
    alelos_rsID = [effect_allele_rsID] + alternate_allele_rsID

    if all(alelo in alelos_rsID for alelo in alelos_original):
        return "Coincide perfecto"

    complementario = {"A": "T", "T": "A", "C": "G", "G": "C"}
    alelos_original_complementario = [complementario.get(alelo, alelo) for alelo in alelos_original]

    if all(alelo in alelos_rsID for alelo in alelos_original_complementario):
        return "Coincide complementario"

    return "No coincide"

In [45]:
df_puro["Valida_alelos"] = df_puro.apply(valida_alelos_SNP, axis = 1)

In [46]:
print(df_puro["Valida_alelos"].value_counts())

Coincide perfecto          898
No coincide                  8
Coincide complementario      3
Name: Valida_alelos, dtype: int64

In [47]:
df_puro = df_puro[df_puro["Valida_alelos"] != "No coincide"].reset_index(drop = True)

In [48]:
df_puro

,Chr,gene_symbol_x,SNPs_symbol,SNP_position,effect_allele,alternate_allele,Chr_corr,inicio,SNP_position_corr,fin,Effect_allele_corr,Alternate_allele_corr,Gene_symbol_corr,fin,Valida_alelos
0,6,GPR126,rs757765789,142758601,T,G,6,142622991,142758601.0,142767403,T,[G],ADGRG6,142767403,Coincide perfecto
1,1,SYT11,rs202015799,155839054,C,T,1,155829300,155839054.0,155854990,C,"[G, T]",SYT11,155854990,Coincide perfecto
2,12,SLC2A13,rs1994090,40428561,G,T,12,40148823,40428561.0,40499891,G,"[A, T, C]",SLC2A13,40499891,Coincide perfecto
3,12,SLC2A13,rs2708453,40478652,G,T,12,40148823,40478652.0,40499891,G,"[A, T]",SLC2A13,40499891,Coincide perfecto
4,12,SLC2A13,rs4768212,40474147,C,T,12,40148823,40474147.0,40499891,C,"[A, T]",SLC2A13,40499891,Coincide perfecto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,17,BRIP1,rs61169879,59917366,T,C,17,59758627,59917366.0,59940882,C,"[A, T]",BRIP1,59940882,Coincide perfecto
897,17,DNAH17,rs666463,76425480,A,T,17,76419778,76425480.0,76573476,A,[T],DNAH17,76573476,Coincide perfecto
898,18,ASXL3,rs1941685,31304318,T,G,18,31158579,31304318.0,31331156,G,"[T, C]",ASXL3,31331156,Coincide perfecto
899,20,CRLS1,rs77351827,6006041,T,C,20,5986736,6006041.0,6020699,C,[T],CRLS1,6020699,Coincide perfecto
900,21,DYRK1A,rs2248244,38852361,A,G,21,38738092,38852361.0,38889753,G,[A],DYRK1A,38889753,Coincide perfecto

In [49]:
complementario = {"A": "T", "T": "A", "C": "G", "G": "C"}

In [50]:
filas_comp = df_puro["Valida_alelos"] == "Coincide complementario"
df_puro.loc[filas_comp, "effect_allele"] = df_puro.loc[filas_comp, "effect_allele"].map(complementario)
df_puro.loc[filas_comp, "alternate_allele"] = df_puro.loc[filas_comp, "alternate_allele"].map(complementario)

In [51]:
df_puro

,Chr,gene_symbol_x,SNPs_symbol,SNP_position,effect_allele,alternate_allele,Chr_corr,inicio,SNP_position_corr,fin,Effect_allele_corr,Alternate_allele_corr,Gene_symbol_corr,fin,Valida_alelos
0,6,GPR126,rs757765789,142758601,T,G,6,142622991,142758601.0,142767403,T,[G],ADGRG6,142767403,Coincide perfecto
1,1,SYT11,rs202015799,155839054,C,T,1,155829300,155839054.0,155854990,C,"[G, T]",SYT11,155854990,Coincide perfecto
2,12,SLC2A13,rs1994090,40428561,G,T,12,40148823,40428561.0,40499891,G,"[A, T, C]",SLC2A13,40499891,Coincide perfecto
3,12,SLC2A13,rs2708453,40478652,G,T,12,40148823,40478652.0,40499891,G,"[A, T]",SLC2A13,40499891,Coincide perfecto
4,12,SLC2A13,rs4768212,40474147,C,T,12,40148823,40474147.0,40499891,C,"[A, T]",SLC2A13,40499891,Coincide perfecto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,17,BRIP1,rs61169879,59917366,T,C,17,59758627,59917366.0,59940882,C,"[A, T]",BRIP1,59940882,Coincide perfecto
897,17,DNAH17,rs666463,76425480,A,T,17,76419778,76425480.0,76573476,A,[T],DNAH17,76573476,Coincide perfecto
898,18,ASXL3,rs1941685,31304318,T,G,18,31158579,31304318.0,31331156,G,"[T, C]",ASXL3,31331156,Coincide perfecto
899,20,CRLS1,rs77351827,6006041,T,C,20,5986736,6006041.0,6020699,C,[T],CRLS1,6020699,Coincide perfecto
900,21,DYRK1A,rs2248244,38852361,A,G,21,38738092,38852361.0,38889753,G,[A],DYRK1A,38889753,Coincide perfecto

In [74]:
df_nuevo.to_csv('datosGene4PD/df_union.csv', index = False)